apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: managed-accelerators
  namespace: accelerator-system
spec:
  serviceAccountName: accelerator-server

  fetch:
  - git:
      url: https://github.com/trisberg/accelerator-samples
      ref: origin/main

  template:
  - ytt: {}
  deploy: 
  - kapp: {}
Footer
